= Challenge Lab
:navtitle: 4: Challenge Lab (Optional)
:numbered:

== Addressing Challenge: 

Feel free to initiate and monitor the entire process for the utensils product. Below are the necessary details to ensure a smooth and comprehensive observation:


== Solution:

. Re-visit the Smart Retail application console, select any utensils product, and share your thoughts, whether positive or constructive, about the product.
+
****
[upperalpha]

.. Find the login details for accessing Smart Retail Application below:
+
TIP: You can skip the login process if you're already signed in.

... *Web Url:* https://globex-web-sentiment-analysis.{openshift_cluster_ingress_domain}[window=_blank]
... *Username:* asilva
... *Password:* openshift
****

. Access the Grafana dashboard to monitor historical sentiments for the utensils product.
+
****
.. Find the login details for accessing RocketChat below:
+
TIP: You can skip the login process if you're already signed in.

... *Grafana URL:* https://grafana-route-influxdb-project.{openshift_cluster_ingress_domain}[window=_blank]
... *Username:* admin
... *Password:* {gitea_admin_password}
****

. Access the RocketChat monitoring system to view the latest message posted by the Automation Controller.
+
****
[upperalpha]

.. Find the login details for accessing RocketChat below:
+
IMPORTANT: Please logout and re-login as pm_utensils if you're already signed in.

... *RocketChat Url:* {rocketchat_url}[window=_blank]
... *Username:* pm_utensils
... *Password:* {rocketchat_admin_password}

.. Navigate to the #utensils channel and review the new message.
****

. As the product manager overseeing Utensils, following a thorough review of the feedback, Try to execute the necessary ChatOps commands in the #utensils channel for the product.

+
****
[NOTE]
====
Here are the three ChatOps action commands available to the Product Manager:

* *Update Price Command:* To update the price of a product, use the command.
+
----
update,ProductID,NewPrice
----

* *Block Product Command:* To block a specific product, issue the command in the respective channel.
+
----
discontinue,ProductID
----

* *Unblock Product Command:* To unblock a specific product, issue the command in the respective channel.
+
----
continue,ProductID
----

Replace ProductID with the product identifier and NewPrice with the updated price for the product

====
****


. Navigate to the Event-driven Ansible console and witness the smooth triggering of the Ansible Controller Job Template. 
+
****
[upperalpha]

.. Find the login details for accessing Event-driven Ansible below:
+
TIP: You can skip the login process if you're already signed in.

... *Event-driven Ansible:* {eda_controller_web_url}[window=_blank]
... *Username:* {eda_controller_admin_user}
... *Password:* {eda_controller_admin_password}
****


. Access the Automation Controller to observe the job triggered by Event-driven Ansible upon posting the ChatOps action in RocketChat. 
+
****
[upperalpha]

.. Find the login details for accessing Automation Controller below:
+
TIP: You can skip the login process if you're already signed in.

... *Automation Controller:* {aap_controller_web_url}[window=_blank]
... *Username:* {aap_controller_admin_user}
... *Password:* {aap_controller_admin_password}
****


. Return to the Smart Retail Application, refresh the page, and locate the same utensil product to verify.


*Thank you for taking on the option challenge lab. Your engagement and effort contribute to a collaborative learning experience. If you have any more challenges or questions, feel free to reach out. Great job!*