
== {lab_name}

=== Workshop Overview


Explore how Red Hat OpenShift combines Machine Learning, CI/CD, and GitOps into a coherent development experience. Participants will learn how Jupyter Notebooks within the Red Hat OpenShift Data Science ecosystem enable dynamic adjustments to applications and models. The workshop will also showcase the power of MLOps via Red Hat OpenShift Pipelines for intelligent application management. Concurrently, attendees will gain insights into GitOps practices, particularly the role of Argo CD in maintaining application resilience. The workshop concludes with a department store scenario, illustrating how these technologies can be applied in a real-world setting to benefit consumers and businesses.


=== Use Cases - To Be Updated
* Common use cases that can be addressed with this architecture are:

** Machine Learning and Real-Time Analytics to build business intelligence.
** Real-time events based on end-user feedback for better product analysis and management.
** Real time interaction with the system with simple Chat Ops-based mechanisms.
** Event driven Ansible using a combination of intelligent applications, Kafka and ChatOps.
** Sentiment analysis.
